/* Autogenerated by /home/yann/linuxcnc-dev/bin/halcompile on Sun Apr 28 17:43:58 2019 -- do not edit */
#include "rtapi.h"
#ifdef RTAPI
#include "rtapi_app.h"
#endif
#include "rtapi_string.h"
#include "rtapi_errno.h"
#include "hal.h"
#include "rtapi_math64.h"

static int comp_id;

#ifdef MODULE_INFO
MODULE_INFO(linuxcnc, "component:rehome2:Re-Home");
MODULE_INFO(linuxcnc, "pin:x:float:0:in::None:None");
MODULE_INFO(linuxcnc, "pin:y1:float:0:in::None:None");
MODULE_INFO(linuxcnc, "pin:y2:float:0:in::None:None");
MODULE_INFO(linuxcnc, "pin:z:float:0:in::None:None");
MODULE_INFO(linuxcnc, "pin:home_x:bit:0:in::None:None");
MODULE_INFO(linuxcnc, "pin:home_y1:bit:0:in::None:None");
MODULE_INFO(linuxcnc, "pin:home_y2:bit:0:in::None:None");
MODULE_INFO(linuxcnc, "pin:home_z:bit:0:in::None:None");
MODULE_INFO(linuxcnc, "funct:_:1:");
MODULE_INFO(linuxcnc, "license:Yann");
MODULE_LICENSE("Yann");
#endif // MODULE_INFO


struct __comp_state {
    struct __comp_state *_next;
    hal_float_t *x;
    hal_float_t *y1;
    hal_float_t *y2;
    hal_float_t *z;
    hal_bit_t *home_x;
    hal_bit_t *home_y1;
    hal_bit_t *home_y2;
    hal_bit_t *home_z;
};
struct __comp_state *__comp_first_inst=0, *__comp_last_inst=0;

static void _(struct __comp_state *__comp_inst, long period);
static int __comp_get_data_size(void);
#undef TRUE
#define TRUE (1)
#undef FALSE
#define FALSE (0)
#undef true
#define true (1)
#undef false
#define false (0)

static int export(char *prefix, long extra_arg) {
    char buf[HAL_NAME_LEN + 1];
    int r = 0;
    int sz = sizeof(struct __comp_state) + __comp_get_data_size();
    struct __comp_state *inst = hal_malloc(sz);
    memset(inst, 0, sz);
    r = hal_pin_float_newf(HAL_IN, &(inst->x), comp_id,
        "%s.x", prefix);
    if(r != 0) return r;
    r = hal_pin_float_newf(HAL_IN, &(inst->y1), comp_id,
        "%s.y1", prefix);
    if(r != 0) return r;
    r = hal_pin_float_newf(HAL_IN, &(inst->y2), comp_id,
        "%s.y2", prefix);
    if(r != 0) return r;
    r = hal_pin_float_newf(HAL_IN, &(inst->z), comp_id,
        "%s.z", prefix);
    if(r != 0) return r;
    r = hal_pin_bit_newf(HAL_IN, &(inst->home_x), comp_id,
        "%s.home-x", prefix);
    if(r != 0) return r;
    r = hal_pin_bit_newf(HAL_IN, &(inst->home_y1), comp_id,
        "%s.home-y1", prefix);
    if(r != 0) return r;
    r = hal_pin_bit_newf(HAL_IN, &(inst->home_y2), comp_id,
        "%s.home-y2", prefix);
    if(r != 0) return r;
    r = hal_pin_bit_newf(HAL_IN, &(inst->home_z), comp_id,
        "%s.home-z", prefix);
    if(r != 0) return r;
    rtapi_snprintf(buf, sizeof(buf), "%s", prefix);
    r = hal_export_funct(buf, (void(*)(void *inst, long))_, inst, 1, 0, comp_id);
    if(r != 0) return r;
    if(__comp_last_inst) __comp_last_inst->_next = inst;
    __comp_last_inst = inst;
    if(!__comp_first_inst) __comp_first_inst = inst;
    return 0;
}
static int default_count=1, count=0;
char *names[16] = {0,};
RTAPI_MP_INT(count, "number of rehome2");
RTAPI_MP_ARRAY_STRING(names, 16, "names of rehome2");
int rtapi_app_main(void) {
    int r = 0;
    int i;
    comp_id = hal_init("rehome2");
    if(comp_id < 0) return comp_id;
    if(count && names[0]) {
        rtapi_print_msg(RTAPI_MSG_ERR,"count= and names= are mutually exclusive\n");
        return -EINVAL;
    }
    if(!count && !names[0]) count = default_count;
    if(count) {
        for(i=0; i<count; i++) {
            char buf[HAL_NAME_LEN + 1];
            rtapi_snprintf(buf, sizeof(buf), "rehome2.%d", i);
            r = export(buf, i);
            if(r != 0) break;
       }
    } else {
        int max_names = sizeof(names)/sizeof(names[0]);
        for(i=0; (i < max_names) && names[i]; i++) {
            if (strlen(names[i]) < 1) {
                rtapi_print_msg(RTAPI_MSG_ERR, "names[%d] is invalid (empty string)\n", i);
                r = -EINVAL;
                break;
            }
            r = export(names[i], i);
            if(r != 0) break;
       }
    }
    if(r) {
        hal_exit(comp_id);
    } else {
        hal_ready(comp_id);
    }
    return r;
}

void rtapi_app_exit(void) {
    hal_exit(comp_id);
}

#undef FUNCTION
#define FUNCTION(name) static void name(struct __comp_state *__comp_inst, long period)
#undef EXTRA_SETUP
#define EXTRA_SETUP() static int extra_setup(struct __comp_state *__comp_inst, char *prefix, long extra_arg)
#undef EXTRA_CLEANUP
#define EXTRA_CLEANUP() static void extra_cleanup(void)
#undef fperiod
#define fperiod (period * 1e-9)
#undef x
#define x (0+*__comp_inst->x)
#undef y1
#define y1 (0+*__comp_inst->y1)
#undef y2
#define y2 (0+*__comp_inst->y2)
#undef z
#define z (0+*__comp_inst->z)
#undef home_x
#define home_x (0+*__comp_inst->home_x)
#undef home_y1
#define home_y1 (0+*__comp_inst->home_y1)
#undef home_y2
#define home_y2 (0+*__comp_inst->home_y2)
#undef home_z
#define home_z (0+*__comp_inst->home_z)


#line 17 "rehome2.comp"

FUNCTION(_) {
static bool _home_x = false;
static bool _home_y1 = false;
static bool _home_y2 = false;
static bool _home_z = false;

static float _x = 0;
static float _y1 = 0;
static float _y2 = 0;
static float _z = 0;

static float _hx = 0;
static float _hy1 = 0;
static float _hy2 = 0;
static float _hz = 0;

//static bool _changed = false;

//static n = 0;
//n++;

if (_home_x == true && home_x == false)
{
  if (_x == 0) _x = x;
  _hx = x;
  rtapi_print_msg(RTAPI_MSG_ERR, "X abs %f rel %f", _hx, _x-_hx);
}

if (_home_y1 == true && home_y1 == false)
{
  if (_y1 == 0) _y1 = y1;
  _hy1 = y1;
  rtapi_print_msg(RTAPI_MSG_ERR, "Y1 abs %f rel %f", _hy1, _y1-_hy1);
}
if (_home_y2 == true && home_y2 == false)
{
  if (_y2 == 0) _y2 = y2;
  _hy2 = y2;
  rtapi_print_msg(RTAPI_MSG_ERR, "Y2 abs %f rel %f", _hy2, _y2-_hy2);
}
if (_home_z == true && home_z == false)
{
  if (_z == 0) _z = z;
  _hz = z;
  rtapi_print_msg(RTAPI_MSG_ERR, "Z abs %f rel %f", _hz, _z-_hz);
}


_home_x = home_x;
_home_y1 = home_y1;
_home_y2 = home_y2;
_home_z = home_z;
}

static int __comp_get_data_size(void) { return 0; }
